### ISSUE TITLE
gnome-shell complain last_focus_time (1659504135) is greater than comparison timestamp (401703).

### ISSUE THREAD

**Issue by yurenchen000** [andyrichardson/simply-workspaces#12]
## version info
```shell
$ gnome-extensions info simply.workspaces@andyrichardson.dev
simply.workspaces@andyrichardson.dev
  Name: Simply Workspaces
  Description: Workspace indication with an i3/polybar style.
  Path: ~/.local/share/gnome-shell/extensions/simply.workspaces@andyrichardson.dev
  URL: https://github.com/andyrichardson/simply-workspaces
  Version: 6
  State: ENABLED

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

$ gnome-shell --version
GNOME Shell 3.36.9
```

## description
Each time switch workspaces by clicking on the indicator,  
gnome-shell complain this warning log:

> $ journalctl -f
gnome-shell[2743]: Window manager warning: last_focus_time (1659504134) is greater than comparison timestamp (400564).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
gnome-shell[2743]: indicator 
gnome-shell[2743]: indicator active
gnome-shell[2743]: Window manager warning: last_focus_time (1659504135) is greater than comparison timestamp (401703).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...

## try to fix
https://github.com/andyrichardson/simply-workspaces/blob/master/extension.js#L71

```diff
    const nodeClick = instance.node.connect("clicked", () => {
-      workspace.activate(Date.now() / 1000);
+      workspace.activate(global.get_current_time());
    });
```

that seems fix the warning log.

// edit ~/.local/share/gnome-shell/extensions/simply.workspaces@andyrichardson.dev/extension.js
// then, restart gnome shell ( Alt+F2 r  Enter)

**Comment by andyrichardson** [comment]
Hey @yurenchen000 thanks for the report. I usually wouldn't be looking to support a version of gnome-shell this old but seeing as you've done the work to fix it, I've gone ahead and made a PR with you as the co-author (#13).

Thanks for your contribution!
