### ISSUE TITLE
Compatibility with Gnome 43

### ISSUE THREAD

**Issue by AdLaurentius** [andyrichardson/simply-workspaces#16]
This is my favourite workspace plugin, but I have upgraded to Gnome 43 and extensions.gnome.org says it is incompatible :(

Just bringing this to your attention, in case you have time to upgrade it :)

Thank you!

**Comment by andyrichardson** [comment]
Thanks for letting me know! It's a bit of a pain to keep up to date with these version numbers - I'd recommend [disabling version checking](https://www.maketecheasier.com/disable-extension-version-checks-gnome/) while you wait for a new release :+1:
