### ISSUE TITLE
Indicator shows all the workspaces, albeit with no windows

### ISSUE THREAD

**Issue by ricpelo** [andyrichardson/simply-workspaces#3]
Hi!

In the `README.md` we can read:

> Note: Similar to polybar, workspaces that have no windows will be hidden

However, using Pop!_OS 21.04 with 10 static workspaces, the indicator shows all the workspace numbers albeit the workspace has no windows.

For example, here I only have a Firefox window on workspace 1 and a gnome-terminal window on workspace 3. There's no more windows in any workspace. However, indicator shows all the workspace numbers from 1 to 10:

![Screenshot from 2021-08-06 20-03-07](https://user-images.githubusercontent.com/616169/128553825-089e2bf5-4e8a-486e-a3ef-4be52e24bda9.png)

**Comment by ricpelo** [comment]
I don't know why, but now I'm unable to reproduce this bug. Maybe I didn't restart Gnome after installing the extension. I'm going to close the issue now and I'll reopen it if I get to reproduce it again.

**Comment by andyrichardson** [comment]
@ricpelo thanks for reporting!

I sometimes get this, will make a patch if I can work out what causes it! I suspect it has something to do with either multiple monitors, or returning from sleep

**Comment by ricpelo** [comment]
> I suspect it has something to do with either multiple monitors, or returning from sleep.

Interesting, because I only have one monitor and my machine never goes to sleep. But yes, I'm using Pop Shell like you.

I'll stay watching, and thank you for your great job!
