### ISSUE TITLE
A small mistake in README.md

### ISSUE THREAD

**Issue by thesilhouettes** [andyrichardson/simply-workspaces#9]
I spotted a small error. Under the "keyboard shortcuts" section in `README.md`, there is a block of code which changes the shortcuts of moving windows to different workspaces:

```
for i in {1..10}
do
   dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-$i "['<Super><Shift>$i']"
done
# Workspace 10 -> 0
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-10 "['<Super><Shift>10']"
```

The last line should have the value `['<Super><Shift>0']` instead of `['<Super><Shift>10']`, just like the code block above it.

**Comment by andyrichardson** [comment]
Thanks for contributing, resolved with #10
